"""add event_images

Revision ID: 6f3105e9fd87
Revises: 63e201a48f68
Create Date: 2025-10-28 12:40:24.766481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f3105e9fd87'
down_revision: Union[str, Sequence[str], None] = '63e201a48f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_images_event_id'), 'event_images', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_images_id'), 'event_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_images_id'), table_name='event_images')
    op.drop_index(op.f('ix_event_images_event_id'), table_name='event_images')
    op.drop_table('event_images')
    # ### end Alembic commands ###
